---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - github.com/chipwolf/architectsmp-gitops/default/minecraft?ref=dev
  - namespace.yaml
patchesStrategicMerge:
  - minecraft-creative.yaml
  - minecraft-proxy-bravo.yaml
  - minecraft-survival.yaml
