---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://charts.helm.sh/stable
      chart: oauth2-proxy
      version: 3.2.5
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: "quay.io/oauth2-proxy/oauth2-proxy"
      tag: "v7.0.1"
    replicaCount: 2
    ingress:
      enabled: true
      path: /oauth2
      hosts: [auth.hrzn.studio]
      tls:
        - hosts:
            - auth.hrzn.studio
    extraArgs:
      provider: oidc
      oidc-issuer-url: https://cwlf.eu.auth0.com/
      skip-provider-button:
      pass-authorization-header:
      email-domain: "*"
      cookie-domain: .hrzn.studio
      whitelist-domain: .hrzn.studio
  valuesFrom:
    - kind: Secret
      name: "oauth2-proxy-helm-values"
      optional: false
