---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-survival
  namespace: default
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 2.1.4
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    # ref: https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml
    image: itzg/minecraft-server
    imageTag: 1.8.0-adopt13
    persistence:
      storageClass: local-path
      dataDir:
        enabled: true
        size: 10Gi
    resources:
      requests:
        memory: 8192Mi
      limits:
        memory: 10240Mi
    extraEnv:
      USE_AIKAR_FLAGS: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
    minecraftServer:
      eula: "TRUE"
      onlineMode: false
      version: "1.16.5"
      mode: survival
      forcegameMode: false
      type: PAPER
      pvp: true
      forceReDownload: true
      difficulty: hard
      playerIdleTimeout: 300
      levelSeed: "-2143500864"
      maxPlayers: 40
      maxWorldSize: 100000
      viewDistance: 12
      maxTickTime: -1
      memory: 8G
      motd: '"\\u00A78-\\u00A7r--\\u00A78-\\u00A7r [ \\u00A7b\\u00A7lArchitect SMP\\u00A7r ] \\u00A78-\\u00A7r--\\u00A78-\\u00A7r [ \\u00A7a\\u00A7lSurvival \\u00A7r] \\u00A78-\\u00A7r--\\u00A78-\\u00A7r\\n\\u00A78-\\u00A7r--\\u00A78-\\u00A7r [ \\u00A7eNews:\\u00A7r ] --\\u00A7r [ \\u00A7ddonate.architectsmp.com\\u00A7r ] \\u00A78-\\u00A7r--\\u00A78-\\u00A7r"'
      serviceType: ClusterIP
      rcon:
        enabled: true
        serviceType: ClusterIP
      dynmap:
        service:
          enabled: true
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - name: map.architectsmp.com
              path: /
