---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy-bravo
  namespace: default
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./releases/bungee-1.3.tgz
      sourceRef:
        kind: GitRepository
        name: architectsmp-charts
        namespace: flux-system
      interval: 5m
  values:
    image: itzg/bungeecord
    imageTag: 1.5.0-adopt13
    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
    bungeeCord:
      type: WATERFALL
      serviceType: LoadBalancer
      externalTrafficPolicy: Local
      memory: 2G
      rcon:
        enabled: true
        serviceType: ClusterIP
